import React, { useState } from 'react';
import axios from 'axios';
import { useLanguage } from '../context/LanguageContext';
import { useAuth } from '../context/AuthContext';
import { 
  Sparkles, Calendar, Banknote, MapPin, Save, 
  Utensils, Bed, Compass, CheckCircle2, RefreshCw 
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { toast } from 'react-hot-toast';

export const AIPlanner = () => {
  const { t, language } = useLanguage();
  const { token } = useAuth();

  // Form states
  const [destination, setDestination] = useState('');
  const [days, setDays] = useState(3);
  const [budget, setBudget] = useState(15000);

  // Result states
  const [itinerary, setItinerary] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);

  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!destination.trim()) {
      toast.error('Please specify a destination.');
      return;
    }

    try {
      setGenerating(true);
      setItinerary(null);
      setSaved(false);

      const response = await axios.post(
        `/api/itineraries/generate?lang=${language}`,
        {
          destination_name: destination,
          num_days: parseInt(days),
          budget: parseFloat(budget),
        }
      );

      setItinerary(response.data);
      toast.success('Itinerary generated by TourEase AI!');
    } catch (err) {
      console.error('Itinerary generation error:', err);
      toast.error('Could not construct itinerary. Check backend server.');
    } finally {
      setGenerating(false);
    }
  };

  const handleSave = async () => {
    if (!token) {
      toast.error(t('authRequiredMsg'));
      return;
    }
    try {
      setSaving(true);
      await axios.post('/api/itineraries/save', {
        destination_name: itinerary.destination || destination,
        num_days: parseInt(itinerary.num_days || days),
        budget: parseFloat(itinerary.budget || budget),
        day_wise_details: JSON.stringify(itinerary)
      });
      setSaved(true);
      toast.success(t('itinerarySavedMsg'));
    } catch (err) {
      console.error('Error saving itinerary:', err);
      toast.error('Failed to save itinerary.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 min-h-screen">
      {/* Header */}
      <div className="text-center max-w-3xl mx-auto mb-10">
        <motion.div
          initial={{ scale: 0.9, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          className="inline-flex p-3 bg-emerald-100 dark:bg-emerald-950 rounded-2xl text-emerald-600 dark:text-emerald-400 mb-4"
        >
          <Sparkles className="w-8 h-8 fill-emerald-500/20" />
        </motion.div>
        <h1 className="text-3xl md:text-4xl font-extrabold text-slate-800 dark:text-white tracking-tight">
          {t('plannerTitle')}
        </h1>
        <p className="text-slate-500 dark:text-slate-400 mt-2">
          {t('plannerSubtitle')}
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        {/* Left Column: Form Parameters */}
        <div className="lg:col-span-4">
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 shadow-sm">
            <h3 className="text-xl font-bold text-slate-850 dark:text-white mb-6">Itinerary Parameters</h3>
            <form onSubmit={handleGenerate} className="space-y-5">
              
              {/* Destination Input */}
              <div className="flex flex-col gap-1.5">
                <label className="text-xs font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1">
                  <MapPin className="w-3.5 h-3.5 text-emerald-500" />
                  <span>{t('fieldDestination')}</span>
                </label>
                <input
                  type="text"
                  placeholder="e.g., Manali, Kerala, Goa"
                  value={destination}
                  onChange={(e) => setDestination(e.target.value)}
                  className="p-3 bg-slate-50 dark:bg-slate-950 text-slate-850 dark:text-slate-100 border border-slate-200 dark:border-slate-800 rounded-xl outline-none focus:border-emerald-500 font-semibold text-sm"
                  required
                />
              </div>

              {/* Days selection */}
              <div className="flex flex-col gap-1.5">
                <label className="text-xs font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1">
                  <Calendar className="w-3.5 h-3.5 text-emerald-500" />
                  <span>{t('fieldDays')}</span>
                </label>
                <input
                  type="number"
                  min="1"
                  max="14"
                  value={days}
                  onChange={(e) => setDays(e.target.value)}
                  className="p-3 bg-slate-50 dark:bg-slate-950 text-slate-850 dark:text-slate-100 border border-slate-200 dark:border-slate-800 rounded-xl outline-none focus:border-emerald-500 font-semibold text-sm"
                  required
                />
              </div>

              {/* Budget input */}
              <div className="flex flex-col gap-1.5">
                <label className="text-xs font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1">
                  <Banknote className="w-3.5 h-3.5 text-emerald-500" />
                  <span>{t('fieldBudget')}</span>
                </label>
                <input
                  type="number"
                  min="1000"
                  step="500"
                  value={budget}
                  onChange={(e) => setBudget(e.target.value)}
                  className="p-3 bg-slate-50 dark:bg-slate-950 text-slate-850 dark:text-slate-100 border border-slate-200 dark:border-slate-800 rounded-xl outline-none focus:border-emerald-500 font-semibold text-sm"
                  required
                />
              </div>

              {/* Submit btn */}
              <button
                type="submit"
                disabled={generating}
                className="w-full py-3.5 bg-emerald-600 hover:bg-emerald-700 text-white font-bold rounded-xl shadow-lg shadow-emerald-600/10 disabled:opacity-50 hover-scale text-sm flex items-center justify-center gap-2"
              >
                {generating ? (
                  <>
                    <RefreshCw className="w-4 h-4 animate-spin" />
                    <span>{t('generatingBtn')}</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4 fill-white" />
                    <span>{t('generateBtn')}</span>
                  </>
                )}
              </button>
            </form>
          </div>
        </div>

        {/* Right Column: Output Result Display */}
        <div className="lg:col-span-8">
          <AnimatePresence mode="wait">
            
            {/* 1. Default Blank/Form Guide */}
            {!generating && !itinerary && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-10 shadow-sm text-center min-h-[300px] flex flex-col justify-center items-center"
              >
                <Compass className="w-16 h-16 text-slate-300 dark:text-slate-700 mb-4 animate-pulse" />
                <h3 className="text-xl font-bold text-slate-800 dark:text-white">Your Itinerary will appear here</h3>
                <p className="text-sm text-slate-500 dark:text-slate-400 mt-2 max-w-md">
                  Specify your travel preferences on the left panel, and our smart Gemini agent will map out stays, local breakfasts, tourist spots, and estimated costs.
                </p>
              </motion.div>
            )}

            {/* 2. Loading State */}
            {generating && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-12 shadow-sm text-center min-h-[300px] flex flex-col justify-center items-center gap-4"
              >
                <div className="relative w-16 h-16">
                  <div className="absolute inset-0 border-4 border-emerald-100 dark:border-emerald-950 rounded-full"></div>
                  <div className="absolute inset-0 border-4 border-emerald-500 border-t-transparent rounded-full animate-spin"></div>
                </div>
                <div>
                  <h3 className="text-xl font-bold text-slate-800 dark:text-white">Formulating Day Plans...</h3>
                  <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
                    Analyzing local attractions, weather conditions, stay accommodations, and local budgets.
                  </p>
                </div>
              </motion.div>
            )}

            {/* 3. Output Itinerary */}
            {itinerary && (
              <motion.div
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                className="space-y-6"
              >
                {/* Result Header Card */}
                <div className="bg-gradient-to-r from-emerald-600 to-teal-500 rounded-3xl p-6 text-white shadow-md flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                  <div>
                    <h2 className="text-2xl font-extrabold tracking-tight">
                      Trip to {itinerary.destination || destination}
                    </h2>
                    <p className="text-emerald-50 text-sm font-semibold mt-1">
                      {itinerary.num_days || days} Days &bull; Budget: ₹{itinerary.budget || budget}
                    </p>
                  </div>
                  
                  {saved ? (
                    <span className="flex items-center gap-1.5 px-4.5 py-2.5 rounded-xl text-sm font-bold bg-emerald-700/60 text-emerald-100 self-start sm:self-center border border-emerald-650">
                      <CheckCircle2 className="w-4.5 h-4.5 text-emerald-250" />
                      Saved
                    </span>
                  ) : (
                    <button
                      onClick={handleSave}
                      disabled={saving}
                      className="flex items-center gap-1.5 px-4.5 py-2.5 rounded-xl text-sm font-bold bg-white text-emerald-700 hover:bg-emerald-50 shadow-md transition-colors self-start sm:self-center"
                    >
                      <Save className="w-4.5 h-4.5" />
                      {saving ? 'Saving...' : t('saveItineraryBtn')}
                    </button>
                  )}
                </div>

                {/* Day-by-Day itinerary list */}
                <div className="space-y-6">
                  {itinerary.days?.map((dayObj, idx) => (
                    <div
                      key={idx}
                      className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 shadow-sm"
                    >
                      {/* Day count header */}
                      <div className="flex items-center gap-2 border-b border-slate-100 dark:border-slate-800 pb-4 mb-4">
                        <Calendar className="w-5 h-5 text-emerald-500" />
                        <h3 className="text-lg font-extrabold text-slate-850 dark:text-white">
                          Day {dayObj.day}
                        </h3>
                      </div>

                      {/* Accommodation card */}
                      {dayObj.accommodation && (
                        <div className="flex items-center gap-3 p-3.5 bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-2xl mb-5">
                          <div className="p-2 bg-blue-100 dark:bg-blue-950 text-blue-600 dark:text-blue-400 rounded-xl">
                            <Bed className="w-4.5 h-4.5" />
                          </div>
                          <div>
                            <p className="text-xs font-bold text-slate-400 uppercase tracking-wider">{t('accomodationLabel')}</p>
                            <p className="text-sm font-bold text-slate-700 dark:text-slate-200">{dayObj.accommodation}</p>
                          </div>
                        </div>
                      )}

                      {/* Day Activities schedule list */}
                      <div className="space-y-4 mb-5">
                        <h4 className="text-xs font-extrabold text-slate-400 uppercase tracking-wider mb-2">Schedule & Sightseeing</h4>
                        <div className="relative border-l-2 border-emerald-100 dark:border-emerald-950 pl-5 ml-2.5 space-y-4">
                          {dayObj.activities?.map((act, actIdx) => (
                            <div key={actIdx} className="relative">
                              {/* Left dot */}
                              <div className="absolute -left-[26px] top-1.5 w-3 h-3 rounded-full bg-emerald-500 border-2 border-white dark:border-slate-900 shadow-sm"></div>
                              
                              <div>
                                <span className="text-xs font-bold text-emerald-600 dark:text-emerald-400 uppercase tracking-wide">
                                  {act.time}
                                </span>
                                <p className="text-sm font-bold text-slate-800 dark:text-slate-100 mt-0.5">
                                  {act.activity}
                                </p>
                                {act.cost > 0 && (
                                  <p className="text-xs font-bold text-slate-400 mt-1">
                                    Est. Entry Fee: ₹{act.cost}
                                  </p>
                                )}
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>

                      {/* Food & Meals suggestions card */}
                      {dayObj.meals && (
                        <div className="border-t border-slate-100 dark:border-slate-800 pt-4">
                          <h4 className="text-xs font-extrabold text-slate-400 uppercase tracking-wider flex items-center gap-1 mb-3">
                            <Utensils className="w-3.5 h-3.5 text-emerald-500" />
                            <span>Dining Plan</span>
                          </h4>
                          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                            <div className="p-3 bg-slate-50 dark:bg-slate-950 rounded-xl">
                              <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">{t('breakfastLabel')}</p>
                              <p className="text-xs font-semibold text-slate-700 dark:text-slate-300 mt-0.5">{dayObj.meals.breakfast || 'Local Delicacies'}</p>
                            </div>
                            <div className="p-3 bg-slate-50 dark:bg-slate-950 rounded-xl">
                              <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">{t('lunchLabel')}</p>
                              <p className="text-xs font-semibold text-slate-700 dark:text-slate-300 mt-0.5">{dayObj.meals.lunch || 'Regional Thali'}</p>
                            </div>
                            <div className="p-3 bg-slate-50 dark:bg-slate-950 rounded-xl">
                              <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">{t('dinnerLabel')}</p>
                              <p className="text-xs font-semibold text-slate-700 dark:text-slate-300 mt-0.5">{dayObj.meals.dinner || 'Speciality Restaurant'}</p>
                            </div>
                          </div>
                        </div>
                      )}
                    </div>
                  ))}
                </div>

                {/* Important Local Tips list */}
                {itinerary.tips && itinerary.tips.length > 0 && (
                  <div className="bg-amber-50/50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-900/50 rounded-3xl p-6 shadow-sm">
                    <h3 className="text-base font-extrabold text-amber-800 dark:text-amber-400 uppercase tracking-wider flex items-center gap-1.5 mb-3">
                      <Sparkles className="w-5 h-5 fill-amber-500/20 text-amber-600" />
                      <span>{t('tipsLabel')}</span>
                    </h3>
                    <ul className="list-disc pl-5 space-y-2 text-sm text-amber-900/90 dark:text-amber-400/90 font-medium">
                      {itinerary.tips.map((tip, idx) => (
                        <li key={idx}>{tip}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
};

export default AIPlanner;
